[colors]
background = '#0c151b8e'
black = '#0c151b'
blue = '#5A768A'
cursor = '#c2c4c6'
cyan = '#2593A8'
foreground = '#c2c4c6'
green = '#718D9C'
magenta = '#9EA0A3'
red = '#97A6AB'
tabs = '#c2c4c6'
tabs-active = '#D5AB9D'
white = '#c2c4c6'
yellow = '#c2c4c6'
dim-black = '#0c151b8e'
dim-blue = '#5A768A8e'
dim-cyan = '#2593A88e'
dim-foreground = '#c2c4c68e'
dim-green = '#718D9C8e'
dim-magenta = '#9EA0A38e'
dim-red = '#97A6AB8e'
dim-white = '#D5AB9D8e'
dim-yellow = '#c2c4c68e'
light-black = '#5A768A'
light-blue = '#2593A8'
light-cyan = '#718D9C'
light-foreground = '#9EA0A3'
light-green = '#97A6AB'
light-magenta = '#D5AB9D'
light-red = '#c2c4c6'
light-white = '#5A768A'
light-yellow = '#2593A8'
