[colors.primary]
background = "#0c151b"
foreground = "#c2c4c6"

[colors.cursor]
text = "#0c151b"
cursor = "#c2c4c6"

[colors.vi_mode_cursor]
text = "#0c151b"
cursor = "#c2c4c6"

[colors.search.matches]
foreground = "#0c151b"
background = "#c2c4c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5b666f"
background = "#c2c4c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0c151b"
red = "#5A768A"
green = "#2593A8"
yellow = "#718D9C"
blue = "#9EA0A3"
magenta = "#97A6AB"
cyan = "#D5AB9D"
white = "#c2c4c6"

[colors.bright]
black = "#5b666f"
red = "#5A768A"
green = "#2593A8"
yellow = "#718D9C"
blue = "#9EA0A3"
magenta = "#97A6AB"
cyan = "#D5AB9D"
white = "#c2c4c6"

[colors.dim]
black = "#c2c4c6"
red = "#5A768A"
green = "#97A6AB"
yellow = "#718D9C"
blue = "#9EA0A3"
magenta = "#2593A8"
cyan = "#D5AB9D"
white = "#5b666f"

