$background = rgb(0c151b)
$foreground = rgb(c2c4c6)
$color0 = rgb(0c151b)
$color1 = rgb(5A768A)
$color2 = rgb(2593A8)
$color3 = rgb(718D9C)
$color4 = rgb(9EA0A3)
$color5 = rgb(97A6AB)
$color6 = rgb(D5AB9D)
$color7 = rgb(c2c4c6)
$color8 = rgb(5b666f)
$color9 = rgb(5A768A)
$color10 = rgb(2593A8)
$color11 = rgb(718D9C)
$color12 = rgb(9EA0A3)
$color13 = rgb(97A6AB)
$color14 = rgb(D5AB9D)
$color15 = rgb(c2c4c6)