--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/hyprtk/Pictures/Wallpapers/9.png"

-- Special
background="#0c151b"
foreground="#c2c4c6"
cursor="#c2c4c6"

-- Colors
color0="#0c151b"
color1="#5A768A"
color2="#2593A8"
color3="#718D9C"
color4="#9EA0A3"
color5="#97A6AB"
color6="#D5AB9D"
color7="#c2c4c6"
color8="#5b666f"
color9="#5A768A"
color10="#2593A8"
color11="#718D9C"
color12="#9EA0A3"
color13="#97A6AB"
color14="#D5AB9D"
color15="#c2c4c6"
