foreground         #c2c4c6
background         #0c151b
background_opacity 1.0
cursor             #c2c4c6

active_tab_foreground     #0c151b
active_tab_background     #c2c4c6
inactive_tab_foreground   #c2c4c6
inactive_tab_background   #0c151b

active_border_color   #c2c4c6
inactive_border_color #0c151b
bell_border_color     #5A768A

color0       #0c151b
color8       #5b666f
color1       #5A768A
color9       #5A768A
color2       #2593A8
color10      #2593A8
color3       #718D9C
color11      #718D9C
color4       #9EA0A3
color12      #9EA0A3
color5       #97A6AB
color13      #97A6AB
color6       #D5AB9D
color14      #D5AB9D
color7       #c2c4c6
color15      #c2c4c6
