# pywal theme for ghostty

background = 0c151b
foreground = c2c4c6
cursor-color = c2c4c6
selection-background = c2c4c6
selection-foreground = 0c151b

palette = 0=#0c151b
palette = 1=#5A768A
palette = 2=#2593A8
palette = 3=#718D9C
palette = 4=#9EA0A3
palette = 5=#97A6AB
palette = 6=#D5AB9D
palette = 7=#c2c4c6
palette = 8=#5b666f
palette = 9=#5A768A
palette = 10=#2593A8
palette = 11=#718D9C
palette = 12=#9EA0A3
palette = 13=#97A6AB
palette = 14=#D5AB9D
palette = 15=#c2c4c6
