general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = ~/.cache/current_wallpaper.png
    blur_passes = 3
    blur_size = 7
    brightness = 0.6
}

label {
    monitor =
    text = $TIME
    color = rgba(c2c5c7ff)
    font_size = 90
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %B %d"
    color = rgba(A19A96ff)
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text =   $USER
    color = rgba(CEC2BDff)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -10
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(A19A96ff)
    inner_color = rgba(0e1722dd)
    font_color = rgba(c2c5c7ff)
    fade_on_empty = true
    placeholder_text = <span foreground="#A19A96">  Enter Password</span>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}
