# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

# Apps

exec-once = awww-daemon &
exec-once = dunst
#exec-once = sleep 5 && pamac-tray-plasma
exec-once = hyprctl setcursor Adwaita 24
exec-once = wl-paste --watch cliphist store
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = wal -R -q

# Scripts

exec-once = bash -c "sleep 3 && cd ~/.local/share/Matuwall && source .venv/bin/activate && LD_PRELOAD=/usr/lib/libgtk4-layer-shell.so matuwall"
exec-once = rm -f /tmp/wobpipe && mkfifo /tmp/wobpipe && tail -f /tmp/wobpipe | wob -c ~/.config/wob/wob.ini &
#exec-once = ~/dotfiles/scripts/octopi.sh
exec-once = ~/dotfiles/scripts/lockscreentime.sh
exec-once = ~/dotfiles/hypr/scripts/wallpaper-restore.sh
exec-once = ~/dotfiles/hypr/scripts/wal-watcher.sh &
exec-once = ~/dotfiles/gtk/gtk.sh
exec-once = cat ~/.cache/wal/colors.Xresources > ~/.Xresources # Update Xresources file with latest wal colours
exec-once = ~/dotfiles/scripts/reset-sudo-attempts.sh
exec-once = ~/dotfiles/scripts/bash-cleanup.sh
exec-once = ~/dotfiles/scripts/set-timezone.sh # set your local timezone in this script

# System

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = xhost +local: # fixes Invalid MIT-MAGIC-COOKIE-1 keyError: cannot open display ':0'